Table users {
    id integer [pk, not null]
    username varchar [unique, not null]
    email varchar [unique, not null]
    first_name varchar
    last_name varchar
    password password [not null]
}

Table settings {
    id integer [pk, not null]
    name varchar [not null]
    description text
}

Table npcs {
    id integer [pk, not null]
    user_id integer [ref: > users.id]
    setting_id integer [ref: > settings.id]
    name varchar [not null]
    race varchar [not null]
    class varchar
    alignment varchar
    background varchar
    strength int
    dexterity int
    constitution int
    intelligence int
    wisdom int
    charisma int
    bond_id integer [ref: > bonds.id]
    flaw_id integer [ref: > flaws.id]
}

Table bonds {
    id integer [pk, not null]
    description text [not null]
}

Table flaws {
    id integer [pk, not null]
    description text [not null]
}

